use super::*;
use crate::dtal::constraints::{Constraint, IndexExpr};
use crate::dtal::regs::{PhysicalReg, VirtualReg};
use std::sync::Arc;
#[test]

fn test_parse_simple_program() {
    let input = r#"; DTAL Program
; Generated by Veritas Compiler

.function main
.returns unit

main:
.main_bb0:
mov v0, 42    ; int
ret
"#;
    let program = parse_dtal(input).unwrap();
    assert_eq!(program.functions.len(), 1);
    assert_eq!(program.functions[0].name, "main");
    assert_eq!(program.functions[0].blocks.len(), 1);
    assert_eq!(program.functions[0].blocks[0].instructions.len(), 2);
}
#[test]

fn test_parse_function_with_params() {
    let input = r#"; DTAL Program
; Generated by Veritas Compiler

.function add
.params {v0: int, v1: int}
.returns int

add:
.add_bb0:
add v2, v0, v1    ; int
mov r0, v2    ; int
ret
"#;
    let program = parse_dtal(input).unwrap();
    assert_eq!(program.functions[0].params.len(), 2);
    assert_eq!(program.functions[0].return_type, DtalType::Int);
}
#[test]

fn test_parse_type_basic() {
    assert_eq!(parse_type_str("int").unwrap(), DtalType::Int);
    assert_eq!(parse_type_str("bool").unwrap(), DtalType::Bool);
    assert_eq!(parse_type_str("unit").unwrap(), DtalType::Unit);
}
#[test]

fn test_parse_type_singleton() {
    assert_eq!(
        parse_type_str("int(42)").unwrap(),
        DtalType::SingletonInt(IndexExpr::Const(42))
    );
}
#[test]

fn test_parse_type_array() {
    let ty = parse_type_str("[int; 10]").unwrap();
    assert_eq!(
        ty,
        DtalType::Array {
            element_type: Arc::new(DtalType::Int),
            size: IndexExpr::Const(10),
        }
    );
}
#[test]

fn test_parse_constraint_simple() {
    let c = parse_constraint_str("v0 >= 0").unwrap();
    assert_eq!(
        c,
        Constraint::Ge(IndexExpr::Var("v0".to_string()), IndexExpr::Const(0))
    );
}
#[test]

fn test_parse_constraint_and() {
    let c = parse_constraint_str("(v0 >= 0 && v0 < 10)").unwrap();
    assert_eq!(
        c,
        Constraint::And(
            Box::new(Constraint::Ge(
                IndexExpr::Var("v0".to_string()),
                IndexExpr::Const(0)
            )),
            Box::new(Constraint::Lt(
                IndexExpr::Var("v0".to_string()),
                IndexExpr::Const(10)
            ))
        )
    );
}
#[test]

fn test_parse_index_expr() {
    assert_eq!(parse_index_expr("42").unwrap(), IndexExpr::Const(42));
    assert_eq!(
        parse_index_expr("v0").unwrap(),
        IndexExpr::Var("v0".to_string())
    );
    assert_eq!(
        parse_index_expr("(v0 + 1)").unwrap(),
        IndexExpr::Add(
            Box::new(IndexExpr::Var("v0".to_string())),
            Box::new(IndexExpr::Const(1))
        )
    );
}
#[test]

fn test_round_trip_simple() {
    use crate::backend::emit::emit_program;

    let input_program = DtalProgram {
        functions: vec![DtalFunction {
            name: "test".to_string(),
            params: vec![(Reg::Virtual(VirtualReg(0)), DtalType::Int)],
            parameter_kinds: vec![],
            return_type: DtalType::Int,
            precondition: None,
            postcondition: None,
            blocks: vec![DtalBlock {
                label: ".test_bb0".to_string(),
                entry_state: TypeState::new(),
                instructions: vec![
                    DtalInstr::MovImm {
                        dst: Reg::Virtual(VirtualReg(1)),
                        imm: 42,
                        ty: DtalType::Int,
                    },
                    DtalInstr::MovReg {
                        dst: Reg::Physical(PhysicalReg::R0),
                        src: Reg::Virtual(VirtualReg(1)),
                        ty: DtalType::Int,
                    },
                    DtalInstr::Ret,
                ],
            }],
        }],
    };

    let text1 = emit_program(&input_program);
    let parsed = parse_dtal(&text1).expect("parse should succeed");
    let text2 = emit_program(&parsed);

    assert_eq!(text1, text2, "Round-trip should produce identical output");
}
