//! DTAL to x86-64 Lowering
//!
//! This module translates DTAL instructions with virtual registers into
//! x86-64 instructions with physical registers.
//!
//! # Pipeline
//!
//! ```text
//! DTAL (virtual regs) → Register Allocation → x86-64 Instructions
//! ```

use crate::backend::dtal::instr::{BinaryOp, CmpOp, DtalFunction, DtalInstr, DtalProgram};
use crate::backend::dtal::regs::Reg;
#[cfg(test)]
use crate::backend::dtal::regs::VirtualReg;
use crate::backend::regalloc::{AllocationResult, GraphColoringAllocator, LinearScanAllocator};
use crate::backend::x86_64::instr::{Condition, MemOperand, X86Function, X86Instr, X86Program};
use crate::backend::x86_64::regs::{Location, X86Reg};

/// Lower a DTAL program to x86-64
pub fn lower_program(program: &DtalProgram) -> X86Program {
    let mut functions = Vec::new();

    for func in &program.functions {
        // Skip runtime stub functions (empty blocks — their machine code
        // is provided by the runtime blob, not generated by the compiler)
        if func.blocks.is_empty() {
            continue;
        }
        functions.push(lower_function(func));
    }

    X86Program { functions }
}

/// Lower a DTAL function to x86-64
fn lower_function(func: &DtalFunction) -> X86Function {
    // Perform register allocation (graph coloring by default, VERITAS_LS=1 for linear scan).
    let allocation = if std::env::var("VERITAS_LS").is_ok() {
        let mut ls_allocator = LinearScanAllocator::new();
        ls_allocator.allocate(func)
    } else {
        let gc_allocator = GraphColoringAllocator::new();
        gc_allocator.allocate(func)
    };

    // Debug allocation
    if std::env::var("VERITAS_DEBUG_ALLOC").is_ok() {
        use crate::backend::regalloc::liveness::{InterferenceGraph, LivenessAnalysis};
        let liveness = LivenessAnalysis::analyze(func);
        let graph = InterferenceGraph::build(func, &liveness);

        eprintln!("=== {} ===", func.name);

        // Dump DTAL
        for block in &func.blocks {
            eprintln!("  {}:", block.label);
            for (i, instr) in block.instructions.iter().enumerate() {
                eprintln!("    {}: {:?}", i, instr);
            }
        }

        // Show allocation
        let mut vregs: Vec<_> = allocation.allocation.keys().copied().collect();
        vregs.sort_by_key(|v| v.0);
        for vreg in &vregs {
            eprintln!("  v{}: {:?}", vreg.0, allocation.allocation.get(vreg));
        }

        // Validate
        for &node in &graph.nodes {
            if let Some(Location::Reg(r1)) = allocation.allocation.get(&node) {
                for neighbor in graph.neighbors(node) {
                    if let Some(Location::Reg(r2)) = allocation.allocation.get(&neighbor)
                        && r1 == r2
                        && node.0 < neighbor.0
                    {
                        eprintln!(
                            "  CONFLICT: v{} and v{} both in {:?}",
                            node.0, neighbor.0, r1
                        );
                    }
                }
            }
        }
    }

    let lowerer = FunctionLowerer::new(func, &allocation);
    lowerer.lower()
}

/// Function lowering context
struct FunctionLowerer<'a> {
    func: &'a DtalFunction,
    allocation: AllocationResult,
    instructions: Vec<X86Instr>,
    /// Stack frame size (for locals and spills)
    frame_size: i32,
    /// Set after a Call instruction; the next read of Physical(R0) should
    /// read from Rax (where x86 puts return values) instead of Rdi.
    return_value_in_rax: bool,
}

impl<'a> FunctionLowerer<'a> {
    fn new(func: &'a DtalFunction, allocation: &AllocationResult) -> Self {
        // Callee-saved registers are pushed between rbp and the spill
        // frame, so spill slot offsets must be shifted down to avoid
        // overlapping with the callee-saved save area.
        let callee_saved_size = (allocation.callee_saved_used.len() as i32) * 8;
        let mut adjusted = allocation.clone();
        for loc in adjusted.allocation.values_mut() {
            if let Location::Stack(offset) = loc {
                *offset -= callee_saved_size;
            }
        }

        // Calculate frame size for spill slots, ensuring 16-byte stack
        // alignment. After the prologue sequence:
        //   push rbp           (rsp -= 8, now rsp % 16 == 8)
        //   N callee-saved     (rsp -= N*8)
        //   sub rsp, frame     (rsp -= frame)
        // We need (8 + N*8 + frame) % 16 == 0 so alloca and calls see
        // a 16-byte-aligned rsp.
        let spill_size = (adjusted.spill_slots as i32) * 8;
        let total_before_frame = 8 + callee_saved_size; // push rbp + callee-saved
        let frame_size = if (total_before_frame + spill_size) % 16 != 0 {
            spill_size + 8 // add 8 bytes padding
        } else {
            spill_size
        };

        Self {
            func,
            allocation: adjusted,
            instructions: Vec::new(),
            frame_size,
            return_value_in_rax: false,
        }
    }

    fn lower(mut self) -> X86Function {
        // Function prologue
        self.emit_prologue();

        // Lower each block
        for block in &self.func.blocks {
            // Emit block label
            self.instructions.push(X86Instr::Label {
                name: block.label.clone(),
            });

            // Lower each instruction
            for instr in &block.instructions {
                self.lower_instruction(instr);
            }
        }

        X86Function {
            name: self.func.name.clone(),
            instructions: self.instructions,
        }
    }

    /// Emit function prologue
    fn emit_prologue(&mut self) {
        // push rbp
        self.instructions.push(X86Instr::Push { src: X86Reg::Rbp });

        // mov rbp, rsp
        self.instructions.push(X86Instr::MovRR {
            dst: X86Reg::Rbp,
            src: X86Reg::Rsp,
        });

        // Save callee-saved registers BEFORE allocating the spill frame.
        // This ensures `mov rsp, rbp; pop` in the epilogue correctly
        // unwinds the saves regardless of any alloca (sub rsp) that
        // happens later in the function body.
        for &reg in &self.allocation.callee_saved_used {
            self.instructions.push(X86Instr::Push { src: reg });
        }

        // Allocate stack frame for spill slots
        if self.frame_size > 0 {
            self.instructions.push(X86Instr::SubRI {
                dst: X86Reg::Rsp,
                imm: self.frame_size,
            });
        }

        // Move arguments from ABI registers to allocated locations.
        // This is a parallel assignment: we must handle the case where
        // a destination register is the source of a later move.
        // e.g. param 0 in Rdi → Rsi, param 1 in Rsi → Rcx would
        // clobber Rsi if done sequentially in order.
        self.emit_param_moves();
    }

    /// Emit function epilogue
    fn emit_epilogue(&mut self) {
        let callee_saved_size = (self.allocation.callee_saved_used.len() as i32) * 8;

        // Restore rsp to point at the last callee-saved push.
        // Layout from prologue:
        //   [rbp]              old rbp
        //   [rbp-8]            callee-saved #1   (first push)
        //   [rbp-16]           callee-saved #2   (second push)
        //   ...
        //   [rbp-N*8]          callee-saved #N   (last push)
        //   [rbp-N*8-frame]    spill slots / alloca
        //
        // mov rsp, rbp sets rsp to [rbp]. sub rsp, N*8 backs it up
        // to [rbp-N*8] so pops restore in reverse push order.
        self.instructions.push(X86Instr::MovRR {
            dst: X86Reg::Rsp,
            src: X86Reg::Rbp,
        });

        if callee_saved_size > 0 {
            self.instructions.push(X86Instr::SubRI {
                dst: X86Reg::Rsp,
                imm: callee_saved_size,
            });
        }

        // Restore callee-saved registers (in reverse order of push)
        for &reg in self.allocation.callee_saved_used.iter().rev() {
            self.instructions.push(X86Instr::Pop { dst: reg });
        }

        // pop rbp
        self.instructions.push(X86Instr::Pop { dst: X86Reg::Rbp });

        // ret
        self.instructions.push(X86Instr::Ret);
    }

    /// Emit parameter moves as a parallel assignment.
    ///
    /// When graph coloring assigns param registers to each other's locations
    /// (e.g., param 0 in Rdi allocated to Rsi, param 1 in Rsi allocated to Rcx),
    /// naive sequential moves would clobber values. We resolve this by:
    /// 1. Processing moves whose destination is NOT a source of another move first
    /// 2. Breaking cycles using R11 as a temporary
    fn emit_param_moves(&mut self) {
        // Collect (src_reg, dst_location) pairs for each parameter
        let mut pending: Vec<(X86Reg, Location)> = Vec::new();

        for (i, (param_reg, _ty)) in self.func.params.iter().enumerate() {
            if let Reg::Virtual(vreg) = param_reg
                && let Some(&src_reg) = X86Reg::ARG_REGS.get(i)
                && let Some(&dst_loc) = self.allocation.allocation.get(vreg)
            {
                // Skip no-op moves (src == dst)
                if dst_loc != Location::Reg(src_reg) {
                    pending.push((src_reg, dst_loc));
                }
            }
        }

        // Resolve parallel moves: emit in an order that avoids clobbering.
        let max_iterations = pending.len() * pending.len() + 1;
        let mut iterations = 0;

        while !pending.is_empty() && iterations < max_iterations {
            iterations += 1;

            // Find a move whose destination register is NOT the source of any OTHER pending move
            let ready_idx = pending.iter().enumerate().position(|(i, (_, dst))| {
                if let Location::Reg(dst_reg) = dst {
                    !pending
                        .iter()
                        .enumerate()
                        .any(|(j, (src, _))| j != i && *src == *dst_reg)
                } else {
                    true // Stack destinations never conflict with sources
                }
            });

            if let Some(idx) = ready_idx {
                let (src, dst) = pending.remove(idx);
                self.store_from_reg(src, dst);
            } else {
                // All remaining moves form cycles. Break with R11 as temp.
                let (first_src, first_dst) = pending.remove(0);
                self.instructions.push(X86Instr::MovRR {
                    dst: X86Reg::R11,
                    src: first_src,
                });
                // Replace first_src with R11 in remaining moves' source
                // so the cycle can continue to resolve
                pending.push((X86Reg::R11, first_dst));
            }
        }
    }

    /// Lower a single DTAL instruction
    fn lower_instruction(&mut self, instr: &DtalInstr) {
        match instr {
            DtalInstr::MovImm { dst, imm, .. } => {
                self.lower_mov_imm(*dst, *imm);
            }

            DtalInstr::MovReg { dst, src, .. } => {
                self.lower_mov_reg(*dst, *src);
            }

            DtalInstr::BinOp {
                op, dst, lhs, rhs, ..
            } => {
                self.lower_binop(*op, *dst, *lhs, *rhs);
            }

            DtalInstr::AddImm { dst, src, imm, .. } => {
                self.lower_add_imm(*dst, *src, *imm);
            }

            DtalInstr::Load {
                dst, base, offset, ..
            } => {
                self.lower_load(*dst, *base, *offset);
            }

            DtalInstr::Store { base, offset, src } => {
                self.lower_store(*base, *offset, *src);
            }

            DtalInstr::Cmp { lhs, rhs } => {
                self.lower_cmp(*lhs, *rhs);
            }

            DtalInstr::CmpImm { lhs, imm } => {
                self.lower_cmp_imm(*lhs, *imm);
            }

            DtalInstr::SetCC { dst, cond } => {
                let x86_cond = match cond {
                    CmpOp::Eq => Condition::E,
                    CmpOp::Ne => Condition::Ne,
                    CmpOp::Lt => Condition::L,
                    CmpOp::Le => Condition::Le,
                    CmpOp::Gt => Condition::G,
                    CmpOp::Ge => Condition::Ge,
                };

                // Always emit setcc into Rax (encoding 0, safe without
                // REX in byte context) then move to the destination.
                // This avoids the entire class of byte-register encoding
                // bugs where codes 4-7 map to AH/CH/DH/BH without REX.
                self.instructions.push(X86Instr::SetCC {
                    dst: X86Reg::Rax,
                    cond: x86_cond,
                });

                let dst_loc = self.get_reg_location(*dst);
                self.store_from_reg(X86Reg::Rax, dst_loc);
            }

            DtalInstr::Not { dst, src, .. } => {
                self.lower_not(*dst, *src);
            }

            DtalInstr::Jmp { target } => {
                self.instructions.push(X86Instr::Jmp {
                    target: target.clone(),
                });
            }

            DtalInstr::Branch { cond, target } => {
                let x86_cond = match cond {
                    CmpOp::Eq => Condition::E,
                    CmpOp::Ne => Condition::Ne,
                    CmpOp::Lt => Condition::L,
                    CmpOp::Le => Condition::Le,
                    CmpOp::Gt => Condition::G,
                    CmpOp::Ge => Condition::Ge,
                };
                self.instructions.push(X86Instr::Jcc {
                    cond: x86_cond,
                    target: target.clone(),
                });
            }

            DtalInstr::Call { target, .. } => {
                // Save caller-saved registers that are in use.
                // The callee may clobber any caller-saved register.
                let mut caller_saved_in_use: Vec<X86Reg> = self
                    .allocation
                    .allocation
                    .values()
                    .filter_map(|loc| match loc {
                        Location::Reg(r) if r.is_caller_saved() => Some(*r),
                        _ => None,
                    })
                    .collect::<std::collections::HashSet<_>>()
                    .into_iter()
                    .collect();
                caller_saved_in_use.sort();

                // Push caller-saved registers
                for &reg in &caller_saved_in_use {
                    self.instructions.push(X86Instr::Push { src: reg });
                }

                // Align stack to 16 bytes before call if needed
                // After pushes, rsp may be misaligned. We need rsp % 16 == 0
                // before the call instruction (which pushes the 8-byte return
                // address, so the callee sees rsp % 16 == 8 — the ABI norm).
                let push_bytes = (caller_saved_in_use.len() as i32) * 8;
                let needs_padding = push_bytes % 16 != 0;
                if needs_padding {
                    self.instructions.push(X86Instr::SubRI {
                        dst: X86Reg::Rsp,
                        imm: 8,
                    });
                }

                self.instructions.push(X86Instr::Call {
                    target: target.clone(),
                });

                // Remove alignment padding
                if needs_padding {
                    self.instructions.push(X86Instr::AddRI {
                        dst: X86Reg::Rsp,
                        imm: 8,
                    });
                }

                // Restore caller-saved registers (reverse order)
                for &reg in caller_saved_in_use.iter().rev() {
                    self.instructions.push(X86Instr::Pop { dst: reg });
                }

                // x86-64 ABI: return value is in RAX. We no longer move it
                // to RDI here because that would clobber any vreg allocated
                // to RDI that is live across the call. Instead, we set a flag
                // so the next read of Physical(R0) reads from RAX directly.
                self.return_value_in_rax = true;
            }

            DtalInstr::Ret => {
                // x86-64 ABI: return value must be in RAX, but DTAL puts it in R0 (mapped to RDI)
                // Copy return value from RDI to RAX before returning
                self.instructions.push(X86Instr::MovRR {
                    dst: X86Reg::Rax,
                    src: X86Reg::Rdi,
                });
                self.emit_epilogue();
            }

            DtalInstr::Push { src, .. } => {
                let loc = self.get_reg_location(*src);
                match loc {
                    Location::Reg(r) => {
                        self.instructions.push(X86Instr::Push { src: r });
                    }
                    Location::Stack(offset) => {
                        let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                        self.instructions.push(X86Instr::MovRM {
                            dst: X86Reg::Rax,
                            src: mem,
                        });
                        self.instructions.push(X86Instr::Push { src: X86Reg::Rax });
                    }
                }
            }

            DtalInstr::Pop { dst, .. } => {
                let loc = self.get_vreg_location(*dst);
                match loc {
                    Location::Reg(r) => {
                        self.instructions.push(X86Instr::Pop { dst: r });
                    }
                    Location::Stack(offset) => {
                        self.instructions.push(X86Instr::Pop { dst: X86Reg::Rax });
                        let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                        self.instructions.push(X86Instr::MovMR {
                            dst: mem,
                            src: X86Reg::Rax,
                        });
                    }
                }
            }

            DtalInstr::Alloca { dst, size, .. } => {
                // Allocate stack space
                let alloc_size = (*size as i32 + 15) & !15; // 16-byte align
                self.instructions.push(X86Instr::SubRI {
                    dst: X86Reg::Rsp,
                    imm: alloc_size,
                });

                // Store pointer in destination
                let loc = self.get_vreg_location(*dst);
                match loc {
                    Location::Reg(r) => {
                        self.instructions.push(X86Instr::MovRR {
                            dst: r,
                            src: X86Reg::Rsp,
                        });
                    }
                    Location::Stack(offset) => {
                        let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                        self.instructions.push(X86Instr::MovMR {
                            dst: mem,
                            src: X86Reg::Rsp,
                        });
                    }
                }
            }

            // Annotations don't generate code
            DtalInstr::TypeAnnotation { .. } | DtalInstr::ConstraintAssert { .. } => {}

            // Physical allocation instructions — these are only present in the
            // physical DTAL pipeline (verify-after-regalloc). The current x86
            // lowering path uses virtual DTAL, so these should not appear here.
            DtalInstr::Cqo
            | DtalInstr::Idiv { .. }
            | DtalInstr::SpillStore { .. }
            | DtalInstr::SpillLoad { .. }
            | DtalInstr::Prologue { .. }
            | DtalInstr::Epilogue { .. } => {
                unreachable!(
                    "Physical DTAL instructions should not appear in virtual DTAL lowering"
                )
            }
        }
    }

    /// Lower mov immediate
    fn lower_mov_imm(&mut self, dst: Reg, imm: i64) {
        let loc = self.get_vreg_location(dst);
        match loc {
            Location::Reg(r) => {
                self.instructions.push(X86Instr::MovRI { dst: r, imm });
            }
            Location::Stack(offset) => {
                // For large immediates or stack destinations, use scratch register
                if imm >= i32::MIN as i64 && imm <= i32::MAX as i64 {
                    let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                    self.instructions.push(X86Instr::MovMI {
                        dst: mem,
                        imm: imm as i32,
                    });
                } else {
                    self.instructions.push(X86Instr::MovRI {
                        dst: X86Reg::R11,
                        imm,
                    });
                    let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                    self.instructions.push(X86Instr::MovMR {
                        dst: mem,
                        src: X86Reg::R11,
                    });
                }
            }
        }
    }

    /// Lower mov register
    fn lower_mov_reg(&mut self, dst: Reg, src: Reg) {
        // After a Call, the return value is in RAX. The DTAL reads it via
        // Physical(R0) which normally maps to RDI, but we must read RAX
        // instead to avoid clobbering a live vreg in RDI.
        let src_loc = if self.return_value_in_rax {
            if let Reg::Physical(preg) = src {
                use crate::backend::dtal::regs::PhysicalReg;
                if preg == PhysicalReg::R0 {
                    self.return_value_in_rax = false;
                    Location::Reg(X86Reg::Rax)
                } else {
                    self.get_reg_location(src)
                }
            } else {
                self.get_reg_location(src)
            }
        } else {
            self.get_reg_location(src)
        };
        let dst_loc = self.get_vreg_location(dst);

        match (src_loc, dst_loc) {
            (Location::Reg(s), Location::Reg(d)) => {
                if s != d {
                    self.instructions.push(X86Instr::MovRR { dst: d, src: s });
                }
            }
            (Location::Reg(s), Location::Stack(offset)) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions.push(X86Instr::MovMR { dst: mem, src: s });
            }
            (Location::Stack(offset), Location::Reg(d)) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions.push(X86Instr::MovRM { dst: d, src: mem });
            }
            (Location::Stack(src_off), Location::Stack(dst_off)) => {
                // Memory to memory: use Rax as scratch (never allocatable)
                let src_mem = MemOperand::base_disp(X86Reg::Rbp, src_off);
                let dst_mem = MemOperand::base_disp(X86Reg::Rbp, dst_off);
                self.instructions.push(X86Instr::MovRM {
                    dst: X86Reg::Rax,
                    src: src_mem,
                });
                self.instructions.push(X86Instr::MovMR {
                    dst: dst_mem,
                    src: X86Reg::Rax,
                });
            }
        }
    }

    /// Lower binary operation
    fn lower_binop(&mut self, op: BinaryOp, dst: Reg, lhs: Reg, rhs: Reg) {
        let lhs_loc = self.get_reg_location(lhs);
        let rhs_loc = self.get_reg_location(rhs);
        let dst_loc = self.get_vreg_location(dst);

        match op {
            BinaryOp::Div | BinaryOp::Mod => {
                // x86 idiv: dividend in rdx:rax, divisor in src reg
                // quotient -> rax, remainder -> rdx
                // Must load rhs first — if rhs is in Rax, loading lhs
                // into Rax second would clobber it.
                let rhs_reg = self.load_to_reg(rhs_loc, X86Reg::R11);
                self.load_to_fixed_reg(lhs_loc, X86Reg::Rax);
                // If rhs was loaded into Rax (because it was allocated
                // there before we reclaim it — not currently possible,
                // but defensive), we need rhs in a different register.
                let divisor = if rhs_reg == X86Reg::Rax {
                    X86Reg::R11
                } else {
                    rhs_reg
                };
                if divisor == X86Reg::Rax {
                    self.instructions.push(X86Instr::MovRR {
                        dst: X86Reg::R11,
                        src: X86Reg::Rax,
                    });
                }
                self.instructions.push(X86Instr::Cqo);
                self.instructions.push(X86Instr::IdivR { src: divisor });
                // Div: quotient in Rax. Mod: remainder in Rdx.
                let result_reg = if op == BinaryOp::Mod {
                    X86Reg::Rdx
                } else {
                    X86Reg::Rax
                };
                self.store_from_reg(result_reg, dst_loc);
            }
            _ => {
                // For non-division: copy lhs into Rax (scratch), operate
                // with rhs in-place, store result from Rax.
                // This avoids clobbering the lhs register which may still
                // be live after this instruction.
                self.load_to_fixed_reg(lhs_loc, X86Reg::Rax);
                let rhs_reg = self.load_to_reg(rhs_loc, X86Reg::R11);

                let instr = match op {
                    BinaryOp::Add => X86Instr::AddRR {
                        dst: X86Reg::Rax,
                        src: rhs_reg,
                    },
                    BinaryOp::Sub => X86Instr::SubRR {
                        dst: X86Reg::Rax,
                        src: rhs_reg,
                    },
                    BinaryOp::Mul => X86Instr::ImulRR {
                        dst: X86Reg::Rax,
                        src: rhs_reg,
                    },
                    BinaryOp::And => X86Instr::AndRR {
                        dst: X86Reg::Rax,
                        src: rhs_reg,
                    },
                    BinaryOp::Or => X86Instr::OrRR {
                        dst: X86Reg::Rax,
                        src: rhs_reg,
                    },
                    BinaryOp::Div | BinaryOp::Mod => unreachable!(),
                };
                self.instructions.push(instr);
                self.store_from_reg(X86Reg::Rax, dst_loc);
            }
        }
    }

    /// Lower add immediate
    fn lower_add_imm(&mut self, dst: Reg, src: Reg, imm: i64) {
        let src_loc = self.get_reg_location(src);
        let dst_loc = self.get_vreg_location(dst);

        // Copy source to Rax to avoid clobbering the source register
        self.load_to_fixed_reg(src_loc, X86Reg::Rax);

        if imm >= i32::MIN as i64 && imm <= i32::MAX as i64 {
            self.instructions.push(X86Instr::AddRI {
                dst: X86Reg::Rax,
                imm: imm as i32,
            });
        } else {
            self.instructions.push(X86Instr::MovRI {
                dst: X86Reg::R11,
                imm,
            });
            self.instructions.push(X86Instr::AddRR {
                dst: X86Reg::Rax,
                src: X86Reg::R11,
            });
        }

        self.store_from_reg(X86Reg::Rax, dst_loc);
    }

    /// Pick a scratch register that doesn't conflict with `avoid`.
    /// Returns one of Rax, Rdx, R11 that isn't in `avoid`.
    fn pick_scratch(avoid: &[X86Reg]) -> X86Reg {
        for &candidate in &[X86Reg::Rax, X86Reg::Rdx, X86Reg::R11] {
            if !avoid.contains(&candidate) {
                return candidate;
            }
        }
        unreachable!("ran out of scratch registers")
    }

    /// Lower load instruction
    fn lower_load(&mut self, dst: Reg, base: Reg, offset: Reg) {
        let base_loc = self.get_reg_location(base);
        let offset_loc = self.get_reg_location(offset);
        let dst_loc = self.get_vreg_location(dst);

        // Load base, picking a scratch that won't conflict
        let base_reg = self.load_to_reg(base_loc, X86Reg::Rax);
        // Load offset, picking a scratch that avoids base_reg
        let offset_scratch = Self::pick_scratch(&[base_reg]);
        let offset_reg = self.load_to_reg(offset_loc, offset_scratch);

        // Load from [base + offset * 8]
        let mem = MemOperand::base_index_disp(base_reg, offset_reg, 8, 0);
        let result_reg = match dst_loc {
            Location::Reg(r) => r,
            Location::Stack(_) => Self::pick_scratch(&[base_reg, offset_reg]),
        };

        self.instructions.push(X86Instr::MovRM {
            dst: result_reg,
            src: mem,
        });

        if let Location::Stack(offset) = dst_loc {
            let dst_mem = MemOperand::base_disp(X86Reg::Rbp, offset);
            self.instructions.push(X86Instr::MovMR {
                dst: dst_mem,
                src: result_reg,
            });
        }
    }

    /// Lower store instruction
    fn lower_store(&mut self, base: Reg, offset: Reg, src: Reg) {
        let base_loc = self.get_reg_location(base);
        let offset_loc = self.get_reg_location(offset);
        let src_loc = self.get_reg_location(src);

        // Load all three operands, picking scratches to avoid conflicts
        let base_reg = self.load_to_reg(base_loc, X86Reg::Rax);
        let offset_scratch = Self::pick_scratch(&[base_reg]);
        let offset_reg = self.load_to_reg(offset_loc, offset_scratch);
        let src_scratch = Self::pick_scratch(&[base_reg, offset_reg]);
        let src_reg = self.load_to_reg(src_loc, src_scratch);

        // Store to [base + offset * 8]
        let mem = MemOperand::base_index_disp(base_reg, offset_reg, 8, 0);
        self.instructions.push(X86Instr::MovMR {
            dst: mem,
            src: src_reg,
        });
    }

    /// Lower cmp instruction
    fn lower_cmp(&mut self, lhs: Reg, rhs: Reg) {
        let lhs_loc = self.get_reg_location(lhs);
        let rhs_loc = self.get_reg_location(rhs);

        let lhs_reg = self.load_to_reg(lhs_loc, X86Reg::Rax);

        match rhs_loc {
            Location::Reg(r) => {
                self.instructions.push(X86Instr::CmpRR {
                    lhs: lhs_reg,
                    rhs: r,
                });
            }
            Location::Stack(offset) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions.push(X86Instr::CmpRM {
                    lhs: lhs_reg,
                    rhs: mem,
                });
            }
        }
    }

    /// Lower cmp immediate instruction
    fn lower_cmp_imm(&mut self, lhs: Reg, imm: i64) {
        let lhs_loc = self.get_reg_location(lhs);
        let lhs_reg = self.load_to_reg(lhs_loc, X86Reg::Rax);

        if imm >= i32::MIN as i64 && imm <= i32::MAX as i64 {
            self.instructions.push(X86Instr::CmpRI {
                lhs: lhs_reg,
                imm: imm as i32,
            });
        } else {
            // Large immediate: pick scratch that doesn't collide with lhs
            let scratch = Self::pick_scratch(&[lhs_reg]);
            self.instructions
                .push(X86Instr::MovRI { dst: scratch, imm });
            self.instructions.push(X86Instr::CmpRR {
                lhs: lhs_reg,
                rhs: scratch,
            });
        }
    }

    /// Lower not instruction
    fn lower_not(&mut self, dst: Reg, src: Reg) {
        let src_loc = self.get_reg_location(src);
        let dst_loc = self.get_vreg_location(dst);

        self.load_to_fixed_reg(src_loc, X86Reg::Rax);
        self.instructions.push(X86Instr::Not { dst: X86Reg::Rax });
        self.store_from_reg(X86Reg::Rax, dst_loc);
    }

    /// Get location of a register (handles both virtual and physical)
    fn get_reg_location(&self, reg: Reg) -> Location {
        match reg {
            Reg::Virtual(vreg) => self.get_vreg_location(Reg::Virtual(vreg)),
            Reg::Physical(preg) => {
                use crate::backend::dtal::regs::PhysicalReg;
                // Map DTAL physical registers to x86-64 ABI registers
                let x86_reg = match preg {
                    PhysicalReg::R0 => X86Reg::Rdi, // 1st arg
                    PhysicalReg::R1 => X86Reg::Rsi, // 2nd arg
                    PhysicalReg::R2 => X86Reg::Rdx, // 3rd arg
                    PhysicalReg::R3 => X86Reg::Rcx, // 4th arg
                    PhysicalReg::R4 => X86Reg::R8,  // 5th arg
                    PhysicalReg::R5 => X86Reg::R9,  // 6th arg
                    PhysicalReg::R6 => X86Reg::R10,
                    PhysicalReg::R7 => X86Reg::R11,
                    PhysicalReg::R8 => X86Reg::Rbx,
                    PhysicalReg::R9 => X86Reg::R12,
                    PhysicalReg::R10 => X86Reg::R13,
                    PhysicalReg::R11 => X86Reg::R14,
                    PhysicalReg::R12 => X86Reg::R15,
                    PhysicalReg::R13 | PhysicalReg::R14 | PhysicalReg::R15 => X86Reg::Rax,
                    PhysicalReg::SP => X86Reg::Rsp,
                    PhysicalReg::FP => X86Reg::Rbp,
                    PhysicalReg::LR => X86Reg::Rax,
                };
                Location::Reg(x86_reg)
            }
        }
    }

    /// Get location of a virtual register from allocation
    fn get_vreg_location(&self, reg: Reg) -> Location {
        match reg {
            Reg::Virtual(vreg) => self
                .allocation
                .allocation
                .get(&vreg)
                .copied()
                .unwrap_or(Location::Reg(X86Reg::Rax)),
            Reg::Physical(preg) => self.get_reg_location(Reg::Physical(preg)),
        }
    }

    /// Load a value from a location into a register.
    ///
    /// If the value is already in a physical register, returns that register
    /// directly (no copy). If spilled to the stack, loads into `scratch`.
    ///
    /// Safety: callers using multiple `load_to_reg` calls in sequence must
    /// ensure that returning existing registers won't cause conflicts. The
    /// register allocator guarantees distinct virtual registers map to
    /// distinct physical registers, so this is safe for loading different
    /// DTAL operands.
    fn load_to_reg(&mut self, loc: Location, scratch: X86Reg) -> X86Reg {
        match loc {
            Location::Reg(r) => r,
            Location::Stack(offset) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions.push(X86Instr::MovRM {
                    dst: scratch,
                    src: mem,
                });
                scratch
            }
        }
    }

    /// Load a value into a specific register (always copies).
    /// Used when the instruction requires the value in a fixed register
    /// (e.g., idiv requires dividend in rax).
    fn load_to_fixed_reg(&mut self, loc: Location, dst: X86Reg) -> X86Reg {
        match loc {
            Location::Reg(r) => {
                if r != dst {
                    self.instructions.push(X86Instr::MovRR { dst, src: r });
                }
            }
            Location::Stack(offset) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions.push(X86Instr::MovRM { dst, src: mem });
            }
        }
        dst
    }

    /// Store a value from a register to a location
    fn store_from_reg(&mut self, reg: X86Reg, loc: Location) {
        match loc {
            Location::Reg(r) => {
                if r != reg {
                    self.instructions.push(X86Instr::MovRR { dst: r, src: reg });
                }
            }
            Location::Stack(offset) => {
                let mem = MemOperand::base_disp(X86Reg::Rbp, offset);
                self.instructions
                    .push(X86Instr::MovMR { dst: mem, src: reg });
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::dtal::instr::{DtalBlock, TypeState};
    use crate::backend::dtal::types::DtalType;

    #[test]
    fn test_lower_simple_function() {
        let v0 = Reg::Virtual(VirtualReg(0));
        let v1 = Reg::Virtual(VirtualReg(1));
        let v2 = Reg::Virtual(VirtualReg(2));

        let func = DtalFunction {
            name: "add".to_string(),
            params: vec![],
            return_type: DtalType::Int,
            precondition: None,
            postcondition: None,
            blocks: vec![DtalBlock {
                label: "entry".to_string(),
                entry_state: TypeState::new(),
                instructions: vec![
                    DtalInstr::MovImm {
                        dst: v0,
                        imm: 10,
                        ty: DtalType::Int,
                    },
                    DtalInstr::MovImm {
                        dst: v1,
                        imm: 20,
                        ty: DtalType::Int,
                    },
                    DtalInstr::BinOp {
                        op: BinaryOp::Add,
                        dst: v2,
                        lhs: v0,
                        rhs: v1,
                        ty: DtalType::Int,
                    },
                    DtalInstr::Ret,
                ],
            }],
        };

        let program = DtalProgram {
            functions: vec![func],
        };

        let x86_program = lower_program(&program);

        assert_eq!(x86_program.functions.len(), 1);
        let x86_func = &x86_program.functions[0];
        assert_eq!(x86_func.name, "add");

        // Should have prologue, body, and epilogue
        assert!(!x86_func.instructions.is_empty());

        // Print instructions for debugging
        for instr in &x86_func.instructions {
            println!("{}", instr);
        }
    }

    #[test]
    fn test_lower_with_branch() {
        use crate::backend::dtal::instr::CmpOp;

        let v0 = Reg::Virtual(VirtualReg(0));

        let func = DtalFunction {
            name: "branch_test".to_string(),
            params: vec![],
            return_type: DtalType::Int,
            precondition: None,
            postcondition: None,
            blocks: vec![
                DtalBlock {
                    label: "entry".to_string(),
                    entry_state: TypeState::new(),
                    instructions: vec![
                        DtalInstr::MovImm {
                            dst: v0,
                            imm: 5,
                            ty: DtalType::Int,
                        },
                        DtalInstr::CmpImm { lhs: v0, imm: 10 },
                        DtalInstr::Branch {
                            cond: CmpOp::Lt,
                            target: "less".to_string(),
                        },
                    ],
                },
                DtalBlock {
                    label: "greater_equal".to_string(),
                    entry_state: TypeState::new(),
                    instructions: vec![
                        DtalInstr::MovImm {
                            dst: v0,
                            imm: 1,
                            ty: DtalType::Int,
                        },
                        DtalInstr::Jmp {
                            target: "exit".to_string(),
                        },
                    ],
                },
                DtalBlock {
                    label: "less".to_string(),
                    entry_state: TypeState::new(),
                    instructions: vec![
                        DtalInstr::MovImm {
                            dst: v0,
                            imm: 0,
                            ty: DtalType::Int,
                        },
                        DtalInstr::Jmp {
                            target: "exit".to_string(),
                        },
                    ],
                },
                DtalBlock {
                    label: "exit".to_string(),
                    entry_state: TypeState::new(),
                    instructions: vec![DtalInstr::Ret],
                },
            ],
        };

        let program = DtalProgram {
            functions: vec![func],
        };

        let x86_program = lower_program(&program);
        let x86_func = &x86_program.functions[0];

        // Should have branch instructions
        let has_jcc = x86_func
            .instructions
            .iter()
            .any(|i| matches!(i, X86Instr::Jcc { .. }));
        let has_jmp = x86_func
            .instructions
            .iter()
            .any(|i| matches!(i, X86Instr::Jmp { .. }));

        assert!(has_jcc, "Should have conditional jump");
        assert!(has_jmp, "Should have unconditional jump");
    }
}
