//! DTAL Text Emitter Implementation
//!
//! This module emits DTAL programs as text files with type annotations.
//! The format is human-readable and includes type state information
//! for verification purposes.

use crate::backend::dtal::Constraint;
use crate::backend::dtal::instr::{
    BinaryOp, CmpOp, DtalBlock, DtalFunction, DtalInstr, DtalProgram,
};
use crate::backend::dtal::regs::Reg;
use crate::backend::dtal::types::DtalType;
use std::fmt::Write;

/// Emit a DTAL program as text
pub fn emit_program(program: &DtalProgram) -> String {
    let mut output = String::new();

    writeln!(output, "; DTAL Program").unwrap();
    writeln!(output, "; Generated by Veritas Compiler").unwrap();
    writeln!(output).unwrap();

    for func in &program.functions {
        emit_function(&mut output, func);
        writeln!(output).unwrap();
    }

    output
}

/// Emit a DTAL function
fn emit_function(output: &mut String, func: &DtalFunction) {
    // Function header
    writeln!(output, ".function {}", func.name).unwrap();

    // Parameters
    if !func.params.is_empty() {
        write!(output, ".params {{").unwrap();
        for (i, (reg, ty)) in func.params.iter().enumerate() {
            if i > 0 {
                write!(output, ", ").unwrap();
            }
            write!(output, "{}: {}", emit_reg(reg), emit_type(ty)).unwrap();
        }
        writeln!(output, "}}").unwrap();
    }

    // Return type
    writeln!(output, ".returns {}", emit_type(&func.return_type)).unwrap();

    // Precondition
    if let Some(ref pre) = func.precondition {
        writeln!(output, ".precondition {}", emit_constraint(pre)).unwrap();
    }

    // Postcondition
    if let Some(ref post) = func.postcondition {
        writeln!(output, ".postcondition {}", emit_constraint(post)).unwrap();
    }

    writeln!(output).unwrap();

    // Entry point label
    writeln!(output, "{}:", func.name).unwrap();

    // Blocks
    for block in &func.blocks {
        emit_block(output, block);
    }
}

/// Emit a basic block
fn emit_block(output: &mut String, block: &DtalBlock) {
    // Block label
    writeln!(output, "{}:", block.label).unwrap();

    // Entry state directives (parseable, not just comments)
    if !block.entry_state.register_types.is_empty() {
        let mut entries: Vec<_> = block.entry_state.register_types.iter().collect();
        entries.sort_by_key(|(reg, _)| emit_reg(reg));
        write!(output, "    .entry {{").unwrap();
        for (i, (reg, ty)) in entries.iter().enumerate() {
            if i > 0 {
                write!(output, ", ").unwrap();
            }
            write!(output, "{}: {}", emit_reg(reg), emit_type(ty)).unwrap();
        }
        writeln!(output, "}}").unwrap();
    }
    if !block.entry_state.owned_registers.is_empty() {
        let mut regs: Vec<_> = block.entry_state.owned_registers.iter().collect();
        regs.sort_by_key(|reg| emit_reg(reg));
        write!(output, "    .owned {{").unwrap();
        for (i, reg) in regs.iter().enumerate() {
            if i > 0 {
                write!(output, ", ").unwrap();
            }
            write!(output, "{}", emit_reg(reg)).unwrap();
        }
        writeln!(output, "}}").unwrap();
    }
    for constraint in &block.entry_state.constraints {
        writeln!(output, "    .assume {}", emit_constraint(constraint)).unwrap();
    }

    // Instructions
    for instr in &block.instructions {
        emit_instruction(output, instr);
    }
}

/// Emit a single instruction
fn emit_instruction(output: &mut String, instr: &DtalInstr) {
    match instr {
        DtalInstr::MovImm { dst, imm, ty } => {
            writeln!(
                output,
                "    mov {}, {}    : {}",
                emit_reg(dst),
                imm,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::MovReg { dst, src, ty } => {
            writeln!(
                output,
                "    mov {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::AliasBorrow { dst, src, ty } => {
            writeln!(
                output,
                "    alias_borrow {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::MoveOwned { dst, src, ty } => {
            writeln!(
                output,
                "    move_owned {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Load {
            dst,
            base,
            offset,
            ty,
        } => {
            writeln!(
                output,
                "    load {}, [{} + {}]    : {}",
                emit_reg(dst),
                emit_reg(base),
                emit_reg(offset),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::LoadOp {
            op,
            dst,
            base,
            offset,
            other,
            ty,
        } => {
            writeln!(
                output,
                "    loadop.{} {}, [{} + {}*8], {}    : {}",
                emit_binop(op),
                emit_reg(dst),
                emit_reg(base),
                emit_reg(offset),
                emit_reg(other),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Store { base, offset, src } => {
            writeln!(
                output,
                "    store [{} + {}], {}",
                emit_reg(base),
                emit_reg(offset),
                emit_reg(src)
            )
            .unwrap();
        }

        DtalInstr::BinOp {
            op,
            dst,
            lhs,
            rhs,
            ty,
        } => {
            writeln!(
                output,
                "    {} {}, {}, {}    : {}",
                emit_binop(op),
                emit_reg(dst),
                emit_reg(lhs),
                emit_reg(rhs),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::AddImm { dst, src, imm, ty } => {
            writeln!(
                output,
                "    addi {}, {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                imm,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Cmp { lhs, rhs } => {
            writeln!(output, "    cmp {}, {}", emit_reg(lhs), emit_reg(rhs)).unwrap();
        }

        DtalInstr::CmpImm { lhs, imm } => {
            writeln!(output, "    cmp {}, {}", emit_reg(lhs), imm).unwrap();
        }

        DtalInstr::SetCC { dst, cond } => {
            writeln!(output, "    set{} {}", emit_cmpop(cond), emit_reg(dst)).unwrap();
        }

        DtalInstr::Not { dst, src, ty } => {
            writeln!(
                output,
                "    not {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Neg { dst, src, ty } => {
            writeln!(
                output,
                "    neg {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::ShlImm { dst, src, imm, ty } => {
            writeln!(
                output,
                "    shli {}, {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                imm,
                emit_type(ty)
            )
            .unwrap();
        }
        DtalInstr::ShrImm { dst, src, imm, ty } => {
            writeln!(
                output,
                "    shri {}, {}, {}    : {}",
                emit_reg(dst),
                emit_reg(src),
                imm,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Jmp { target } => {
            writeln!(output, "    jmp {}", target).unwrap();
        }

        DtalInstr::Branch { cond, target } => {
            writeln!(output, "    b{} {}", emit_cmpop(cond), target).unwrap();
        }

        DtalInstr::Call {
            target,
            arg_ownerships,
            return_ty,
            ownership,
        } => {
            let mnemonic = match ownership {
                crate::common::ownership::OwnershipMode::Plain => "call",
                crate::common::ownership::OwnershipMode::Consume => "call_consume",
                crate::common::ownership::OwnershipMode::FreshOwned => "call_owned",
            };
            let arg_suffix = if arg_ownerships.is_empty() {
                String::new()
            } else {
                let effects = arg_ownerships
                    .iter()
                    .map(|mode| match mode {
                        crate::common::ownership::OwnershipMode::Plain => "plain",
                        crate::common::ownership::OwnershipMode::Consume => "consume",
                        crate::common::ownership::OwnershipMode::FreshOwned => "fresh",
                    })
                    .collect::<Vec<_>>()
                    .join(",");
                format!(" [{}]", effects)
            };
            writeln!(
                output,
                "    {} {}{}    : {}",
                mnemonic,
                target,
                arg_suffix,
                emit_type(return_ty)
            )
            .unwrap();
        }

        DtalInstr::Ret => {
            writeln!(output, "    ret").unwrap();
        }

        DtalInstr::Push { src, ty } => {
            writeln!(output, "    push {}    : {}", emit_reg(src), emit_type(ty)).unwrap();
        }

        DtalInstr::Pop { dst, ty } => {
            writeln!(output, "    pop {}    : {}", emit_reg(dst), emit_type(ty)).unwrap();
        }

        DtalInstr::Alloca { dst, size, ty } => {
            writeln!(
                output,
                "    alloca {}, {}    : {}",
                emit_reg(dst),
                size,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::DropOwned { src, ty } => {
            writeln!(
                output,
                "    drop_owned {}    : {}",
                emit_reg(src),
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::PortIn { dst, port } => {
            writeln!(output, "    port_in {}, {}", emit_reg(dst), emit_reg(port)).unwrap();
        }

        DtalInstr::PortOut { port, value } => {
            writeln!(
                output,
                "    port_out {}, {}",
                emit_reg(port),
                emit_reg(value)
            )
            .unwrap();
        }

        DtalInstr::Cqo => {
            writeln!(output, "    cqo").unwrap();
        }

        DtalInstr::Idiv { src } => {
            writeln!(output, "    idiv {}", emit_reg(src)).unwrap();
        }

        DtalInstr::SpillStore { src, offset, ty } => {
            writeln!(
                output,
                "    spill_store {}, [rbp{}]    : {}",
                emit_reg(src),
                offset,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::SpillLoad { dst, offset, ty } => {
            writeln!(
                output,
                "    spill_load {}, [rbp{}]    : {}",
                emit_reg(dst),
                offset,
                emit_type(ty)
            )
            .unwrap();
        }

        DtalInstr::Prologue {
            frame_size,
            callee_saved,
        } => {
            let regs: Vec<_> = callee_saved.iter().map(emit_reg).collect();
            writeln!(
                output,
                "    .prologue frame={} callee_saved=[{}]",
                frame_size,
                regs.join(", ")
            )
            .unwrap();
        }

        DtalInstr::Epilogue { callee_saved } => {
            let regs: Vec<_> = callee_saved.iter().map(emit_reg).collect();
            writeln!(output, "    .epilogue callee_saved=[{}]", regs.join(", ")).unwrap();
        }

        DtalInstr::TypeAnnotation { reg, ty } => {
            writeln!(output, "    .type {}: {}", emit_reg(reg), emit_type(ty)).unwrap();
        }

        DtalInstr::ConstraintAssert { constraint } => {
            writeln!(output, "    .assert {}", emit_constraint(constraint)).unwrap();
        }
    }
}

/// Emit a register
fn emit_reg(reg: &Reg) -> String {
    match reg {
        Reg::Virtual(vreg) => format!("v{}", vreg.0),
        Reg::Physical(preg) => format!("{:?}", preg).to_lowercase(),
    }
}

/// Emit a binary operation
fn emit_binop(op: &BinaryOp) -> &'static str {
    match op {
        BinaryOp::Add => "add",
        BinaryOp::Sub => "sub",
        BinaryOp::Mul => "mul",
        BinaryOp::Div => "div",
        BinaryOp::Mod => "mod",
        BinaryOp::BitAnd => "bitand",
        BinaryOp::BitOr => "bitor",
        BinaryOp::BitXor => "bitxor",
        BinaryOp::Shl => "shl",
        BinaryOp::Shr => "shr",
        BinaryOp::And => "and",
        BinaryOp::Or => "or",
    }
}

/// Emit a comparison operation
fn emit_cmpop(op: &CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "eq",
        CmpOp::Ne => "ne",
        CmpOp::Lt => "lt",
        CmpOp::Le => "le",
        CmpOp::Gt => "gt",
        CmpOp::Ge => "ge",
    }
}

/// Emit a type
fn emit_type(ty: &DtalType) -> String {
    // DtalType's Display impl already produces the correct format
    ty.to_string()
}

/// Emit a constraint
fn emit_constraint(constraint: &Constraint) -> String {
    // Constraint's Display impl already produces the correct format
    constraint.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backend::dtal::VirtualReg;
    use crate::backend::dtal::instr::TypeState;

    #[test]
    fn test_emit_simple_function() {
        let func = DtalFunction {
            name: "test".to_string(),
            params: vec![(Reg::Virtual(VirtualReg(0)), DtalType::Int)],
            return_type: DtalType::Int,
            precondition: None,
            postcondition: None,
            blocks: vec![DtalBlock {
                label: ".test_bb0".to_string(),
                entry_state: TypeState::new(),
                instructions: vec![
                    DtalInstr::MovImm {
                        dst: Reg::Virtual(VirtualReg(1)),
                        imm: 42,
                        ty: DtalType::Int,
                    },
                    DtalInstr::Ret,
                ],
            }],
        };

        let program = DtalProgram {
            functions: vec![func],
        };

        let output = emit_program(&program);
        assert!(output.contains(".function test"));
        assert!(output.contains("mov v1, 42"));
        assert!(output.contains("ret"));
    }
}
